version: '3.8'
services:
  franquicias-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franquicias-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
